MD013:
  # Number of characters
  line_length: 120

MD033:
  allowed_elements:
  - img  # for images with custom formatting
  - br   # for linebreaks e.g. in tables
  - div  # for formatting like centering images
